spring:
  profiles:
    active: local
    group:
      local: oauth

  jpa:
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect

    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE

  h2:
    console:
      enabled: true
